# Generated by Django 5.0.1 on 2024-01-07 02:43

import utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('biography', models.TextField(blank=True, null=True)),
                ('hype', models.TextField(blank=True, null=True)),
                ('primary_attr', models.CharField(choices=[('strength', 'Strength'), ('agility', 'Agility'), ('intelligence', 'Intelligence'), ('universal', 'Universal')])),
                ('attack_type', models.CharField(choices=[('melee', 'Melee'), ('ranged', 'Ranged')])),
                ('roles', utils.fields.ChoiceArrayField(base_field=models.CharField(choices=[('carry', 'Carry'), ('disabler', 'Disabler'), ('durable', 'Durable'), ('escape', 'Escape'), ('initiator', 'Initiator'), ('jungler', 'Jungler'), ('nuker', 'Nuker'), ('pusher', 'Pusher'), ('support', 'Support')]), size=None)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='media/heroes/avatars/')),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('dota_name', models.CharField(max_length=255)),
                ('dota_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Hero',
                'verbose_name_plural': 'Heroes',
                'ordering': ['name'],
            },
        ),
    ]
